{
  page(id: "cGFnZToxNQ==") {
    title
    content
    featuredImage{
      mediaItemUrl
    }
    nosotros{
      fotoInformacion{
        mediaItemUrl
        altText
      }
      informacion
      mision
      vision
      valor1
      iconoValor1
      valor2
      iconoValor2
      valor3
      iconoValor3
      representante1
      rol1
      foto1{
        mediaItemUrl
      }
      frase
    }
  }
}