{
  page(id: "cGFnZToxOA==") {
    id
    title
    featuredImage {
      mediaItemUrl
    }
    contacto{
      imagenOficina{
        mediaItemUrl
      }
      correo
      telefono
      direccion
      mapa
    }
  },
  redesSociales {
    edges {
      node {
        redes{
          facebook
          youtube
          whatsapp
        }
      }
    }
  }
}