{
  page(id: "cGFnZToxOA==") {
    id
    title
    featuredImage {
      mediaItemUrl
    }
    contacto{
      imagenOficina{
        mediaItemUrl
      }
      telefono
      direccion
      mapa
    }
  }
}