{
  redesSociales {
    edges {
      node {
        title
        redes{
          facebook
          whatsapp
          youtube
          direccion
          celular
          correo
        }
      }
    }
  },
  page(id: "cGFnZToxOA==") {
    contacto{
      imagenOficina{
        mediaItemUrl
      }
      correo
      telefono
      direccion
      mapa
    }
  }
}