{
  redesSociales {
    edges {
      node {
        title
        redes{
          facebook
          whatsapp
          youtube
          direccion
          celular
          correo
        }
      }
    }
  }
}