{
  page(id: "cGFnZToxMw=="){
    title
    content
    featuredImage{
      mediaItemUrl
      altText
    }
    home{
      publicaciones
      imagenPublicacion {
        mediaItemUrl
        altText
      }
    }
  }
}